-- phpMyAdmin SQL Dump
-- version 4.0.6deb1
-- http://www.phpmyadmin.net
--
-- Host: localhost
-- Generation Time: Jan 27, 2015 at 12:54 PM
-- Server version: 5.5.37-0ubuntu0.13.10.1
-- PHP Version: 5.5.3-1ubuntu2.6

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Database: `_maps_`
--

-- --------------------------------------------------------

--
-- Table structure for table `_companies_`
--

CREATE TABLE IF NOT EXISTS `_companies_` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `_name_` varchar(150) DEFAULT NULL,
  `_website_` varchar(200) DEFAULT NULL,
  `_type_` varchar(100) DEFAULT NULL,
  `_desc_` varchar(2000) DEFAULT NULL,
  `_city_` varchar(100) DEFAULT NULL,
  `_address_` varchar(200) DEFAULT NULL,
  `_contact_details_` varchar(300) DEFAULT NULL,
  `_rating_` varchar(10) NOT NULL,
  `_longitude_` varchar(50) NOT NULL,
  `_latitude_` varchar(50) NOT NULL,
  `sts` varchar(2) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=72 ;

--
-- Dumping data for table `_companies_`
--

INSERT INTO `_companies_` (`id`, `_name_`, `_website_`, `_type_`, `_desc_`, `_city_`, `_address_`, `_contact_details_`, `_rating_`, `_longitude_`, `_latitude_`, `sts`) VALUES
(2, 'Hatchstation', 'http://hatchstation.com/', 'Co-Working Places', 'HatchStation is an ecosystem for startups in Hyderabad to co-work, live and prosper from ideation to profitable ventures.', 'Hyderabad', 'BEGUMPET OFFICE,19/3RT, Prakash Nagar, Begumpet, Hyderabad - 500016. ', 'Phone:+91 90325 90328     ,                                                           chinna@hatchstation.com, www.hatchstation.com   ', '', '', '', '1'),
(3, 'CoWorkZone', 'http://www.coworkzone.in/', 'Co-Working Place', 'Cowork Zone has plug and play office space arranged in private, lockable cabins. Work Stations and Manager seating are laid out within cabins. The office space is of modern, contemporary design', 'Hyderabad', 'Address: Road No 12, Venkateswara Colony, Banjara Hills, Hyderabad, Telangana', 'info@coworkzone.in                                               coworkzone.in', '', '', '', '2'),
(4, 'The Valley', 'http://thevalley.in/', 'Co-Working Place', 'At The Valley, we believe in people and their entrepreneurial spirit. We sought to build a community of like-minded doers visionaries, change makers & problem solvers. \nWe realized epic stuff happens where more than one motivated person gathers with the intention to work and create shared value for the benefit of the community.', 'Hyderabad', 'The Valley, 8-2-351/GG6\nRoad Number 3, Banjara Hills\nHyderabad, Telangana 500034\nIndia', '91-8008799756,                                                                 +91-996337729                                    sharjeelsidd808@gmail.com                                    http://thevalley.in/                                                                 ', '', '', '', '2'),
(5, 'ikeva', 'www.ikeva.in', 'Co-Working Place', 'iKeva is your destination for a plug and play office space in upscale locations across India. With a premier team at its disposal, iKeva can be your pitstop for fully serviced office space that comes with value-added services.', 'Hyderabad', 'Level 1, am@10, \nMB Towers, \nRoad No. 10, Banjara Hills\nHyderabad, India - 500 034.', 'Tel - +91 40 4646 4889\nFax - +91 40 4646 4890                                         contact@ikeva.in                                              http://www.ikeva.in/', '', '', '', '1'),
(6, 'CIE-IIIT Incubator', 'http://iiith.org/', 'Co-Working Place', 'CIE @ IIIT campus has been established with the goal to promote innovation and entrepreneurship. Amongst the various facets of CIE-IIIT, Coworking space is one of the support feature', 'Hyderabad', 'International Institute of Information Technology \nGachibowli, Hyderabad 500 032 \n Telangana, INDIA\n                    ', ' Phone : +91-40-6653 1000 \n Fax : +91-40-6653 1413                                      contact@iiith.org                                                             www.iiith.org', '', '', '', '1'),
(7, 'UPTEC IDEALABS', 'www.uptecidealabs.com', 'Co-Working Place', 'UPTEC IDEALABS provides coworking space with plug and play facility on Engineering College campus across several regions. This helps the college and students to watch Innovation In Action on their campus and provide local startups the much needed infrastructure and skilled manpower/interns', 'Hyderabad', 'Corporate Office: #401, Jade Aracde , Paradise , Secunderabad-03', '91-7660891111                                        www.uptecidealabs.com', '', '', '', '1'),
(8, 'Lamakaan', 'www.lamakaan.com/', 'Event Hosting venue', 'Lamakaan is an inclusive cultural space that promotes and presents the best of arts, literature, debate and dialogue with a commitment to being open and accessible.Lamakaan is yours. Do what you will with it.', 'Hyderabad', 'Road No. 1, Banjara Hills, Hyderabad. It is in the lane next to the Vengala Rao Park, opposite GVK One Mall.', '91-96427 31329  ,  http://www.lamakaan.com', '', '', '', '1'),
(9, 'ShareDesk', 'http://www.sharedesk.net/', 'Co-Working Space Listing/ marketplace', 'ShareDesk marketplace provides a platform for mobile professionals to discover and book work and meeting spaces on the go by the hour, day, or month. We have a network of over 2,400 venues in all corners of the globe and powering thousands of reservations each day. Pay for what you use, and work where you need to.', 'Hyderabad', '', '', '', '', '', '1'),
(10, 'Coworkable', 'http://coworkable.com/', 'Coworking  Space Portal', 'Coworkable.com is a global platform to Find + Rent or List, Shared Office Spaces, Coworking Spaces, Hacker Spaces or Skills for Startups, Individuals, Freelancers, Home Offices and Small & Medium Businesses.', 'Hyderabad', '', 'ping@coworkable.com https://www.facebook.com/Coworkable', '', '', '', '1'),
(11, 'Jack your Start Up', '', 'Co Working Space', 'Jack Your Start Up is one stop solution for all your start-up need, right from co-working spaces to Mentoring.We help you to build your own dream start-up', 'Hyderabad', 'MLA Colony Road No.12,Banjara Hills, Hyderabad 500034', 'http://www.jackyourstartup.com/', '', '', '', '1'),
(12, 'RentADesk', 'http://www.rentadesk.in/', 'Co-Working Space ', 'Rent A Desk provides workspace solutions and networking opportunities in a suitable environment equipped with the right infrastructure to ignite your ideas and fuel your work flow without burning a hole in your pocket. Sharing your work space with potential entrepreneurs, creative individuals and other professionals overrides the prospects of working by yourself at home.', 'Hyderabad', '8-2-348/1, 202, 2nd Floor,\nFlora Apartments, Road # 3, Banjara Hills, Hyderabad.', '\n+91 98 85 421400                                     info@rentadesk.in                                      www.rentadesk.in', '', '', '', '1'),
(13, 'Co.Lab.Orate', 'http://www.colaborate.in/', 'Co-Working Space', 'We are a community coworking space. Our participants at Co.Lab.Orate are recognized more by their talent rather than their identity or domain in which they operate. A pleasant crowd full of energy and smiles is what you can expect at our space.', 'Hyderabad', 'fLAT #102,Siddhartha Residency\nKavuri Hills Phase 1, Kavuri Hills, Madhapur\nHyderabad, Telangana 500033', 'Phone: +91-9985190002/04/06\n\nEmail: enquiries@colaborate.in', '', '', '', '1'),
(14, 'Regus', 'http://www.regus.co.in', 'Co-Working Space/Day Office/Meeting Rooms', 'We know that start-up companies need to stay flexible and keep overheads low in order to succeed.\n\nWe also know you want to be taken seriously.\n\nSo we have a range of products and services designed to help you set up quickly, easily and at the right price, while still projecting a professional image.', 'Hyderabad', 'Several Locations across Hyderabad', 'Phone: 1800 209 4949 | + 91 22 4026 0000', '', '', '', '1'),
(15, 'ServCorp', 'http://www.servcorp.co.in/en/', 'Co Working Space/Day Office/Meeting Room', 'We are committed to being the world''s finest Serviced and Virtual Office provider, and we believe in adding value to your business by exceeding your expectations and giving detailed attention to the little things.\n\nServcorp is the Serviced and Virtual Office industry leader in innovation and the development of technology to benefit your business. This gives you more time and money to spend on your primary business activities.', 'Hyderabad', 'Level 7, Maximus Towers, Building 2A, Mindspace Complex, Hi-Tech City, Hyderabad-500 081', 'http://www.servcorp.co.in/en/', '', '', '', '1'),
(16, 'iHub', 'http://ihubhyd.com/', 'Co-Working Space (Serviced and Virtual)', 'iHub offers affordable serviced office & virtual offices for startups with no long term lease.\niHub is a super flexible and affordable office solution for starups.\niHub dramatically increases your overall productivity.', 'Hyderabad', 'iHub Jubilee Hills\n4th Floor, Tirumala Mansion\nPlot 120, Kavuri Hills, Phase I\nJubilee Hills,\nHyderabad\nIndia 500033', 'phone : +91-9652419892\nemail  : hello@ihubhyd.com            http://ihubhyd.com/', '', '', '', '1'),
(17, 'LaunchPad', 'http://www.launchpadit.in/', 'Co-Working Space', 'LAUNCH PAD  is an alternative to traditional serviced or home offices. Suited to individuals and small businesses, we offer first class desk space in great locations. Giving  you full access to all the office and meeting room facilities that you require, helping you to focus on whats really important. Growing your business.', 'Hyderabad', 'Plot No: 286, Ayyappa Society,  \nMadhapur, Hyderabad, \nAndhra Pradesh 500082', 'Email: hello@launchpadit.in\nPhone:00919502123450\n                040 6550 4444 ', '', '', '', '1'),
(18, 'Roots', 'http://rootsindia.wordpress.com/', 'Co-Working Space', 'We will reinforce sharing and collaboration through proven practices of gift based economics and exchange while forming synergy and productivity of diverse parties via the utilization of a Coworking & Coliving space', 'Hyderabad', 'A 36 Durgabhai Deshmukh Colony, Baghamberpet, Hyderabad AP 500013', 'Mallik Posanipalli\n\ndiycommunityspace@gmail.com\n', '', '', '', '1'),
(19, 'CollabHouse', 'http://http://collab.house/', 'Co-Working Space', 'Inspiring workspace for individuals and organizations. Cowork with amazing people in a collaborative, supportive environment. Get access to dozens of partnered coworking spaces with the Coworking Visa.', 'Hyderabad', ' - 32, 3rd Floor,\nRoad No. 5, Film Nagar,\nJubilee Hills\nHyderabad 500 033', 'Phone : +91 9985258603                           www.collab.house', '', '', '', '1'),
(20, 'CoKArma', 'http://www.cokarma.in/', 'Co-Working Space', 'CoKarma is a CoWorking space and a community of entrepreneurs, freelancers and creatives who work in a shared office space to help each other succeed. It has the right infrastructure, location and services to kickstart your startup business.\nIt is located in the heart of Hyderabad and provides an affordable launchpad for entrepreneurs.', 'Hyderabad', '309, Liberty Plaza\n3-6-365, Himayat Nagar\nHyderabad', 'Phone:91 99 89 016041\nEmail: dropin@cokarma.in', '', '', '', '1'),
(21, 'Startup Leadership Program (SLP)', 'http://www.startupleadership.com/', 'Mentoring', 'The Startup Leadership Program (SLP) is a highly selective, 80-hour, 6-month world-class training program and lifetime network for outstanding founders and innovators. SLP Fellows have founded 1,000 companies that have raised $400 million, and include breakthrough and award-winning startups like Savored, TomNod, Ixigo, NatureBox, SideTour, Micello, Momelan, Novira, Runkeeper, Sensobi, Shareaholic, Solar Junction, Voicetap and Ubersense.', 'Hyderabad', '', '', '', '', '', '1'),
(22, 'Founders Institute (FI)', 'http://fi.co/', 'Mentoring', 'The Founder Institute is the world''s largest entrepreneur training and startup launch program, helping aspiring founders across the globe build enduring technology companies.', 'Hyderabad', '', '', '', '', '', '1'),
(23, 'Lean Startup Machine (LSM)', 'https://www.leanstartupmachine.com/', 'Mentoring', 'Lean Startup Machine is a three-day workshop where you will learn how to apply Lean Startup methodologies to build things customers love paying for! No matter where you are in the process, well show you a step-by-step process to develop a product that customers actually want.', 'Hyderabad', '', '', '', '', '', '1'),
(24, 'Centre for Social Initiative and Management (CSIM)', 'http://www.csim.in/', 'Mentoring', 'CSIM launched a centre in Hyderabad in 2002, by networking with Dr.Reddys Foundation. This centre has emerged as a prominent learning and networking centre for social workers, NGOs and budding social entrepreneurs in Hyderabad. The Centre has already trained over 250 persons and most of them are now active agents for social change and development.', 'Hyderabad', '', '', '', '', '', '1'),
(25, 'YI Hyd (Young Indians)', 'http://www.youngindians.net/', 'Industry Body', 'Young Indians (Yi) is an integral part of the Confederation of Indian Industry (CII), a non-government, not-for-profit, industry led and industry managed organisation playing a proactive role in India''s development process. Yi was formed in the year 2002 with an objective of creating a platform for young Indians to realise the dream of a developed nation. Yi has around 1650 direct members in 33 chapters, and engages around 10500 students through student nets, under the brand Yuva.Yi engages its members under the board categories of education, environment, healthcare, employability, arts (sports & culture) and rural initiatives contributing positively to its surrounding eco system and the nation', '', '', '', '', '', '', '1'),
(26, 'CII(Confederation of Indian Industry )', 'http://www.cii.in/', 'Industry Body', 'The Confederation of Indian Industry (CII) works to create and sustain an environment conducive to the growth of industry in India, partnering industry and government alike through advisory and consultative processes.Itcovering various aspects such as finance and taxation, foreign direct investment, banking, insurance, WTO and international trade, disinvestment, small and medium enterprises, defence, elections and industrial relations.', '', '', '', '', '', '', '1'),
(27, 'TiE (The Indus Entrepreneurs)', 'https://www.tie.org/', 'Entrepreneur', 'The Indus Entrepreneurs (TiE), was founded in 1992 in Silicon Valley by a group of successful entrepreneurs, corporate executives, and senior professionals with roots in the Indus region. There are currently 11,000 members, including over 2,500 charter members in 60 chapters across 17 countries. TiEs mission is to foster entrepreneurship globally through mentoring, networking, and education. Dedicated to the virtuous cycle of wealth creation and giving back to the community, TiEs focus is on generating and nurturing our next generation of entrepreneurs.TiE Young Entrepreneurs (TYE) program to foster entrepreneurship in our youth, and TiE Womens Forum for empowering women entrepreneurs.', '', '', '', '', '', '', '1'),
(28, 'HYSEA', 'http://hysea.in/', 'Industry Body', 'The Hyderabad Software Enterprises Association, HYSEA (Formerly The IT & ITES Industry Association of AP, ITsAP ) is a registered apex body with more than 300 members, representing the software industry in Hyderabad under the AP Public Societies Registration Act. The Association represents the interests of the IT, ITES and Software Products Industry, both Domestic & Export Oriented units in the state of Hyderabad, including Tier II cities.', '', '', '', '', '', '', '1'),
(29, 'Eat Sleep Drink Startups', 'http://www.esdstartups.com/', 'Startup', 'ESD Startups is a voluntarY/revolutionarY/crazY organization that helps Young People chase their dreams ! It is driven by a bunch of passionate and madly comitted individuals who eat sleep drink startups day in and day out ! We build/do activities and workshops that help aspiring entrepreneurs, film makers and other commited young folks with great ideas !.Founded a couple of years back by a rather irrational startup guy, ESD Startups now operates outstanding platforms like The August Fest, Friday Film Festival, Hyderabad Business Summit and StartupGarage.', '', '', '', '', '', '', '1'),
(30, 'BNI (Business Network International)', 'http://www.bni.com/', 'Industry Body', 'With over 170,000 members worldwide, BNI is the largest business networking organization in the world. Last year alone, BNI generated 5.4 million referrals resulting in $6.5 billion dollars'' worth of business for its members. We offer members the opportunity to share ideas, contacts and most importantly, business referrals.The mission of BNI is to help members increase their business through a structured, positive, and professional "word-of-mouth" program that enables them to develop long-term, meaningful relationships with quality business professionals.', '', '', '', '', '', '', '1'),
(31, 'NASSCOM', 'www.nasscom.in', 'Industry Body/Entrepreneur', 'NASSCOM is the industry association for the IT-BPM sector in India. A not-for-profit organisation funded by the industry, its objective is to build a growth led and sustainable technology and business services sector in the country.\nEstablished in 1988, NASSCOMs membership has grown over the years and currently stands at 1,400. These companies represent 95 percent of industry revenues and have enabled the association to spearhead initiatives and programs to build the sector in the country and globally.', '', '', '', '', '', '', '1'),
(32, 'Hyderabad Hackers', 'hyderabadhackers.in', 'Startup Consortium', 'An ecosystem initiative anchored by HYSEA to nurture and grow an environment of technology and product programming hackers. The various organizations that form Hyderabadhackers.in includes devthon.org (by PiSutra), Uptec Idealabs, Startup Weekend, Hyderabad Entrepreneurs Society, Startup Hyderabad, Fests.info, Null Hyderabad and Coding Saturdays. Anchored by Hysea.', '', '', '', '', '', '', '1'),
(33, 'The August Fest', 'http://theaugustfest.com/', 'Events', 'The August Fest is a first-of-its kind event that celebrates art and entrepreneurship in India. Meet like-minded innovators, trailblazers, entrepreneurs, filmmakers, musicians, fashion designers, photographers, and other creative professionals to bond, connect and share ideas.\n\n', '', '', '', '', '', '', '1'),
(34, 'Nascomm Product Conclave', 'http://productconclave.in/', 'Events', 'nasscom event ', '', '', '', '', '', '', '1'),
(35, 'Techsparks ', 'http://techsparks.yourstory.com/2014/', 'Events', 'TechSparks, an initiative undertaken by YourStory.in, Indias popular digital media platform for startups, entrepreneurs and SMBs, is aimed at bridging the gap between the potential of product technology companies in India and the opportunities for them to scale, by bringing together the entire technology ecosystem which involves investors, experienced entrepreneurs, developers, corporates and the media under a single roof.', '', '', '', '', '', '', '1'),
(36, 'ISB iDiya', 'http://events.isb.edu/idiya/', 'Events', 'iDiya invites applications from teams, with ongoing ventures, or with ventures that are yet to be implemented, in the social space. Ten teams are then shortlisted, and invited on all on expenses paid trip to ISB for an intensive one week boot camp', '', '', '', '', '', '', '1'),
(37, 'Microsoft Bizspark India startup challenge ', 'www.microsoft.com/bizspark/', 'Events', 'Microsoft BizSpark India Startup Challenge is an annual event which provides a platform to identify and promote upcoming promising startups in India who are providing a product in the field of connected devices and continuous services.', '', '', '', '', '', '', '1'),
(38, 'Techniche ', '', 'Events', 'It is with this ideal in mind that Techniche and the Entrepreneurial Development Cell, IIT Guwahati presents to you Startup Showcase, an event wherein the most successful startups share their ideas and experiences, their magical journey to success and the pitfalls in their path.', '', '', '', '', '', '', '1'),
(39, 'Think Big Women in Business Forum 2014', 'http://weconnectinternational.org/en/india', 'Events', 'Recognising that womens enterprises are still small and need to equip themselves to scale up and reach new market opportunities, WEConnect International is organizing their second Think Big 2014 Women in Business Forum on 11-12 September 2014, at Bangalore, India.', '', '', '', '', '', '', '1'),
(40, 'Techcircle Startup 2014', 'http://events.vccircle.com/content/techcircle-startup-2014', 'Events', 'To capture the latest and lasting excitement in the Indian tech ecosystem, Techcircle launches its new edition of Techcircle Startup 2014 on 26-27 February, Bengaluru.', '', '', '', '', '', '', '1'),
(41, 'UnPluggd', 'http://startupsunplugged.com/', 'Events', 'UnPluggd is NextBigWhat s flagship event and is a melting pot of individuals who discover, evaluate and build a technology business. It is launchpad for Technology Startups (demoed startups have raised more than $30mn since their demo @UnPluggd). UnPluggd previous editions has seen speakers like the founders of Slideshare, Flipkart, InMobi, Mast Kalandar, Vaatsalya Hospitals, RedBus, Burrp talking about their journey, the struggle, failure and importantly, lessons learnt.', '', '', '', '', '', '', '1'),
(42, 'Startup Festival', 'http://www.startupfestival.in/', 'Events', 'To celebrate rising of Bangalore as a startup city, TiE Bangalore in association with Unstoppable.in came up with an idea of a festival where startups can meet, learn from each other, get to know about trends and new strategies. A festival that would be featuring 75+ sessions at 60 venues with more than 50 speakers. They got more than 100 festival partners, participating 60 startups along with 500 founders.', '', '', '', '', '', '', '1'),
(43, 'TiE Events', 'http://tiecon.org/', 'Events', 'TIE (The Indus Entrepreneurs) is a global nonprofit dedicated to fostering entrepreneurship. TiE has 57 chapters in 14 countries, with a total membership exceeding 13,000. TiE is most closely affiliated with the South Asian business community, and is recognized as an important networking forum for entrepreneurs and investors. TiEs sponsors include nearly every venture capital firm in Silicon Valley. The World Affairs Council of Northern California held its 2002 annual gala in honor of TiE for TiEs contributions to the international community and to global commerce.', '', '', '', '', '', '', '1'),
(44, 'Indian Angel Networks Events', 'http://www.indianangelnetwork.com/', 'Events', 'In its continuous endeavour to work for seed and early stage entrepreneurs, Indian Angel Network (IAN), the pioneer of Angel Investing in India, has established the IAN Incubator with the support of National Science and Technology Entrepreneurship Development Board, Department of Science & Technology, Govt. of India. IAN Incubator provides a platform for sound technology/business ideas to become successful and investible businesses at the time when they are most susceptible the first few months before and after the creation of the venture. The IAN Incubator supports techno-preneurs along their entire journey from an idea to enterprise and beyond.', '', '', '', '', '', '', '1'),
(45, 'IN50HRS', 'http://www.in50hrs.com/', 'Events', 'In50hrs, is a idea to prototype event conducted by The Startup Centre, which curates and pushes your startup idea to accelerate. If you want to be a technology entrepreneur, this is a perfect event to start working with your idea.', '', '', '', '', '', '', '1'),
(46, 'Startup roots', 'http://www.nextbigwhat.com/announcing-startuproots-this-saturday-april-20th-live-funding-amazing-speakers-shark-tanks-and-more-297/', 'Events', 'The nextbigwhat team in partnership with 10000 startups announced #startuproot, an event packed with amazing speakers, live funding, shark tanks and more. ', '', '', '', '', '', '', '1'),
(47, 'Startup Saturday', 'http://startupsaturday.headstart.in/', 'Events', 'Under the umbrella of the Headstart Foundation is a monthly networking hub for entrepreneurs across five cities. Startup Saturday kick started in Bangalore in March 2008 and subsequently the concept spread to Mumbai, Delhi, Hyderabad and Kolkata. ', '', '', '', '', '', '', '1'),
(48, 'Construkt Festival ', 'http://construkt.me/', 'Events', 'Construkt Festival is a 4 day conference for entrepreneurs and creators across 4 communities (tech, design, culinary, social). We''re catalyzing cross-disciplinary connection through workshops, panels, presentations, art installations, performances and more.', '', '', '', '', '', '', '1'),
(49, 'Hyderebad Hackers events', 'hyderabadhackers.in', 'Events', 'several events to strengthen startip ecosystem by Hyderabad Hackers. Some of the current events revolve around Devthons', '', '', '', '', '', '', '1'),
(50, 'Startup Specialists group', 'https://www.linkedin.com/groups/Startup-Specialists-Group-Online-Network-56766/about', 'online forum', 'A Startup Specialists Group - Online Network for Entrepreneurs and Startups (Mentors Experts Business Jobs Careers) is the LARGEST moderated (members only) community for startups, mentors, founders, investors and small business experts on LinkedIn.', '', '', '', '', '', '', '1'),
(51, 'Next Big What', 'http://www.nextbigwhat.com/', 'Website', 'NextBigWhat is our biggest and most ambitious plan around covering technology startups globally and importantly, connect global entrepreneurs with each other.', '', '', '', '', '', '', '1'),
(52, 'www.beanentrepreneur.com', 'http://www.beanentrepreneur.com/', 'Website', 'portal for entrepeneurs.Serve as a business mentor for all aspiring and budding entrepreneurs\nHelp you analyse your bright idea to see whether it is viable\nConnect you with key business people and customers\nProvide a fresh perspective on how to grow your business\nAct as a sounding board to discuss difficulties (tax consultancy and statutory requirements)\nHelp you to sort out your business finances.', '', '', '', '', '', '', '1'),
(53, 'Startup Hyderabad', 'http://startuphyderabad.com/', 'website', 'About Start-Up Hyderabad StartupHyderabad.com is your destination for comprehensive news, information and the latest happenings in Hyderabads startup ecosystem. This unique venture aims to provide detailed news coverage of all the exciting, new startups in Hyderabad and bring to limelight the impact, innovation and leadership brought about by a vibrant and buzzing fraternity of entrepreneurs Our goal is to provide the latest news, trends and events to help entrepreneurs and startup enthusiasts to succeed in their mission. ', '', '', '', '', '', '', '1'),
(54, 'whatsupstartup', 'http://www.petsanta.in/whatupstartup/whatupstartup1', 'website', 'There is a colossal collection of blogs, podcasts and other tips on the web for startups and founders - how much of that is truly actionable?Everything about Whatup Startup is designed to be action oriented, be it our content or our services.', '', '', '', '', '', '', '1'),
(55, 'yourstory.in', 'http://yourstory.com/', 'website', 'YourStory.com is Indias biggest and definitive platform for startups and entrepreneurs related stories, news, resources, research reports.YourStory.com is Indias no.1 media platform for entrepreneurs, dedicated to passionately championing and promoting the entrepreneurial ecosystem in India.YourStory hosts Indias most loved and wide-reaching conferences for entrepreneurs including TechSparks, MobiSparks, E-Sparks, WebSparks, EduStars, Cloud Conclave, Startup Jobs Fair, Sociopreneurship and various other meetups and workshops rallying the entire entrepreneurship ecosystem in India onto one platform facilitating meaningful conversations and partnerships.', '', '', '', '', '', '', '1'),
(56, 'INC42.com', 'http://inc42.com/category/entrepreneurship/', 'Website', 'A website featuring several things including focussed section on Startups and entrepreneurship success stories and issues related to startups', '', '', '', '', '', '', '1'),
(57, 'Mentor Resources', 'http://500.co/mentors', 'Website', 'directory of mentors in several areas', '', '', '', '', '', '', '1'),
(58, 'Hackathons', 'Hyderabadhackers.in', 'Website', 'Hyderabad hackers website provides all the information around startup space in hyderabad', '', '', '', '', '', '', '1'),
(59, 'CIE-IIIT', 'http://iiith.org/', 'Incubator', 'We support technology intensive startups through a variety of programs such as Launchpad and incubation', 'Hyderabad', '', 'srinivas.k@iiith.org', '', '', '', '1'),
(60, 'Progress Pacific Incubator', 'https://www.progress.com/incubator', 'Incubator', 'The Progress Pacific Incubator program aims to mentor early stage startups in building business applications from prototype to completion by providing access to the companys Pacific platform, reduce the barrier to entry by providing space and infrastructure, and providing advisory access to Progress substantial R&D expertise. The vision is to enable startups to create the next generation of business applications leveraging the low-cost, with faster time-to-market, high-productivity solutions provided by the Pacific platform, through the 6-month pacific Cohort program for seed-stage startups.', 'Hyderabad', '', 'Progress Software Dev Private LTD\nAddress: iLAB''s Centre, 4th Floor, #18\nSoftware Units Layout, Madhapur\nHyderabad, INDIA 500 081\n\nPhone: 91-40-4510-6000\nFax: 91-40-4510-2222', '', '', '', '1'),
(61, 'UTTISHTA CAPITAL', 'http://www.utthishta.com/', 'Seedfund', 'We are a seed fund for start-ups in software, web, mobile and the cloud computing space, but that description does not quite describe the experience we provide for entrepreneurs. We provide a combination of seed funding along with focused mentoring to early stage startups for a small piece of equity. The amount of money that we provide is good to get you through the early stage expenses of your company', 'Hyderabad', '', 'contact@utthishta.net', '', '', '', '1'),
(62, 'MICROSOFT VENTURES', 'http://www.microsoftventures.com/', 'Accelerator', 'Welcome to Microsoft Ventures Accelerator, India. The goal of our four-month program is to produce high potential startups from the ecosystem by providing deep engagement to strengthen and grow customer traction. The program, which draws out the very best from the entrepreneur, encourages startups to ask for help in aspects of technology, user experience, design and go-to-market strategy leading to access to high quality mentors, partners, customers and technologists.', 'Bangalore (presence in Hyderabad)', '', 'msvindia@microsoft.com', '', '', '', '1'),
(63, 'HYDERABAD ANGELS', 'http://hyderabadangels.in/', 'Angel Investors', 'One of the youngest but the fastest growing angel networks in India, Hyderabad Angels is established as a not for profit company that provides a vehicle for the introduction of individual angel investors to potential high growth companies.We believe in quality rather than quantity , seeking only the most diverse and high potential businesses for our discerning investors.\nWe receive up to 80 business plans each month from entrepreneurs looking for equity investment to grow their businesses. We carefully review each of these, selecting 4-5 high growth companies that match our investment criteria and present to our investors.\nSelected companies will formally pitch their investment proposition to our investors who meet on a monthly basis; usually upto three companies present to the angels at such an event.', 'Hyderabad', '', 'Info@hyderabadangels.in', '', '', '', '1'),
(64, 'DLABS', 'www.dlabs.in/', 'Incubator', 'We are a business incubator at The Indian School of Business. We leverage an immersive and transformative Human-Centered Design (HCD) process to build the next generation of companies.', 'Hyderabad', '', '91 40 2300 7000', '', '', '', '1'),
(65, 'Wadhwani Centre for Entrepreneurship Development, Indian School of Business (ISB)', 'http://www.isb.edu/wadhwani-centre-for-entrepreneurship-development', 'Incubator', 'At WCED, we are committed to entrepreneurship as a transformational vehicle for the broad-based growth of India and other developing economies. The centre aims to enable creation and growth of sustainable and competitive enterprises through innovative research, outreach and pilot initiatives.', 'Hyderabad', '', 'Ph +91 40 2300 7000,Fax +91 40 2300 7099', '', '', '', '1'),
(66, '50K VENTURES', 'http://www.50kventures.com/ventures/', 'Seedfund', 'A platform for tech startups \nat the earliest stage of \ntheir life-cycles, providing\n access to seed funds, connecting\n with dedicated mentors and\n launching into different markets. \nIt is also a great place for investors\n and experts to find, fund and nurture\n ground-breaking ideas that will change\n the world', 'Hyderabad', '', 'info@50kventures.com', '', '', '', '1'),
(67, 'BITS Pilani- TBI', 'http://www.bits-pilani.ac.in/hyderabad/tbi', 'Incubator', 'Does the name redBus ring a bell? The company is one of those that have been started by alumni of BITS Pilani. Many others look to follow suit and are incubated at the TBI at BITS Pilani.\nSet up in 2002, the business incubator has incubated about 15 companies so far. While most of the startups based at the incubator are those started by students from the BITS Pilani campus, the incubator also has a virtual incubator program for those who are based outside this particular campus.\nThe startups receive funds through the government grant that the incubator receives.\nThe Centre for Entrepreneurial Leadership which works closely with the TBI at BITS Pilani also helps startups interact with VCs and angels to help them receive investments.', 'Hyderabad', '', 'tbi@hyderabad.bits-pilani.ac.in , +91 9010200768', '', '', '', '1'),
(68, 'Venture EAST', 'http://ventureast.net/', 'Venture Capitalists', 'Ventureast is a pioneering Indian VC fund manager with close to $300 million under management. We have a rich history of investing in innovative businesses across multiple sectors, and multiple stages of a business - from seed and early to growth stages', 'Hyderabad', '', '+91-40-2335 1044 / 45 / 46, 6551 0491', '', '', '', '1'),
(69, 'IKP Life Science Incubator', 'www.ikpknowledgepark.com', 'incubator', 'IKP Knowledge Park has set up a Life Science Incubator (LSI) with an incubation space of around 3,200 sft. for 8 incubatees to encourage and nurture startup companies and spin offs in pharmaceutical and biotechnology related areas. The LSI was set up with the support of National Science and Technology Entrepreneurship Development Board (NSTEDB) of Dept. of Science and Technology (DST) Government of India. The LSI includes a 3,200 sft. Life Sciences Incubator with fully furnished dedicated lab space, shared equipment and an assistance programme that is expected to benefit innovative start-up companies and scientist entrepreneurs.', 'Hyderabad', '', '040-23480022', '', '', '', '1'),
(70, 'UPTEC IDEALABS', 'www.uptecidealabs.com', 'Incubator', 'A unique approach to foster entrepreneurship on college campuses across India. Also, a Co-Workplace provided to local entrepreneurs to bring the culture of Innovation and entrepreneurship on campus , provide interns to startups', 'Hyderabad', '', '04066320014/24', '', '', '', '1'),
(71, '', '', '', '', '', '', '', '', '', '', '1');

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
